spec:
  name: cloudcollab
  region: tor1
  services:
    - name: edge
      instance_count: 1
      instance_size_slug: basic-xxs
      http_port: 8080
      source_dir: /
      image:
        registry_type: DOCR
        registry: registry.digitalocean.com
        repository: cloudcollab/edge
        tag: latest
      health_check:
        http_path: /healthz
      envs:
        - key: FRONTEND_ORIGIN
          scope: RUN_TIME
          value: "http://__FRONTEND_IP__/"
        - key: BACKEND_ORIGIN
          scope: RUN_TIME
          value: "http://__BACKEND_IP__:8000/"